In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("melb_data.csv")

In [2]:
new=df.isna().sum()

In [37]:
percentage=new/len(df) * 100

In [5]:
percentage

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price             0.000000
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.000000
Postcode          0.000000
Bedroom2          0.000000
Bathroom          0.000000
Car               0.456554
Landsize          0.000000
BuildingArea     47.496318
YearBuilt        39.580265
CouncilArea      10.081001
Lattitude         0.000000
Longtitude        0.000000
Regionname        0.000000
Propertycount     0.000000
dtype: float64

In [46]:
 b=percentage[percentage>20].index

In [47]:
df=df.drop(b,axis=1)

In [49]:
df.head(3)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

In [51]:
#----2
df.fillna(df.median(numeric_only=True), inplace=True)

In [54]:
categorial_columns=df.select_dtypes(include=["object"]).columns

In [55]:
for col in categorial_columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

<ipython-input-55-4d7dc19786ff>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [56]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [61]:
#TASK 2 , PART1
values=df[(df["Suburb"]== "Richmond")& (df["Price"]>100000)]

In [63]:
values.head(2)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
5256,Richmond,24 Butler St,2,h,937000.0,S,Biggin,3/09/2016,2.6,3121.0,2.0,1.0,1.0,125.0,Yarra,-37.8106,144.9940,Northern Metropolitan,14949.0
5257,Richmond,81 Erin St,3,h,1260000.0,S,Biggin,3/09/2016,2.6,3121.0,2.0,1.0,0.0,203.0,Yarra,-37.8166,144.9945,Northern Metropolitan,14949.0

In [71]:
lsz=df.loc[df["Landsize"]>500, ["Price", "Suburb", "CouncilArea"]]

In [72]:
lsz

           Price          Suburb    CouncilArea
20     1330000.0      Abbotsford          Yarra
22     1090000.0      Abbotsford          Yarra
45      720000.0    Airport West  Moonee Valley
46      785000.0    Airport West  Moonee Valley
47      725000.0    Airport West  Moonee Valley
...          ...             ...            ...
13570   970000.0  Wantirna South       Moreland
13571  1330000.0  Wantirna South       Moreland
13573   635000.0        Werribee       Moreland
13575  1245000.0   Wheelers Hill       Moreland
13578  2500000.0    Williamstown       Moreland

[6175 rows x 3 columns]

In [73]:
sorted_values=df.sort_values(by="Price", ascending=False)

In [74]:
sorted_values.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
12094,Mulgrave,35 Bevis St,3,h,9000000.0,PI,Hall,29/07/2017,18.8,3170.0,3.0,1.0,1.0,744.0,Monash,-37.93168,145.16126,South-Eastern Metropolitan,7113.0
7692,Canterbury,49 Mangarra Rd,5,h,8000000.0,VB,Sotheby's,13/05/2017,9.0,3126.0,5.0,5.0,4.0,2079.0,Boroondara,-37.81790,145.06940,Southern Metropolitan,3265.0
9575,Hawthorn,49 Lisson Gr,4,h,7650000.0,S,Abercromby's,17/06/2017,5.3,3122.0,4.0,2.0,4.0,1690.0,Boroondara,-37.82652,145.03052,Southern Metropolitan,11308.0
3616,Kew,15 Barry St,6,h,6500000.0,S,Jellis,13/08/2016,5.6,3101.0,6.0,6.0,3.0,1334.0,Boroondara,-37.80290,145.02670,Southern Metropolitan,10331.0
12557,Middle Park,136 Page St,5,h,6400000.0,S,Marshall,9/09/2017,3.0,3206.0,5.0,2.0,1.0,553.0,Moreland,-37.84908,144.95753,Southern Metropolitan,2019.0

In [75]:
#-----Task3
df["Price_per_room"]=df["Price"]/df["Rooms"]

In [76]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Price_per_room
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,740000.000000
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,517500.000000
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,488333.333333
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,283333.333333
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,400000.000000

In [81]:
df["Date"]=pd.to_datetime(df["Date"], format="%d/%m/%Y", errors="coerce")

In [78]:
df.head(1)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Price_per_room
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,740000.0

In [82]:
df["Year_sold"]=df["Date"].dt.year

In [84]:
# task -----4
average_price=df.groupby("Suburb")["Price"].mean()

In [85]:
average_price

Suburb
Abbotsford      1.060366e+06
Aberfeldie      1.277455e+06
Airport West    7.566567e+05
Albanvale       5.370833e+05
Albert Park     1.941355e+06
                    ...
Wonga Park      9.000000e+05
Wyndham Vale    4.832500e+05
Yallambie       8.396875e+05
Yarra Glen      6.200000e+05
Yarraville      9.886155e+05
Name: Price, Length: 314, dtype: float64

In [86]:
total_properties=df.groupby("Suburb")["Price"].count()

In [87]:
total_properties

Suburb
Abbotsford       56
Aberfeldie       44
Airport West     67
Albanvale         6
Albert Park      69
               ...
Wonga Park        1
Wyndham Vale      4
Yallambie        24
Yarra Glen        1
Yarraville      164
Name: Price, Length: 314, dtype: int64

In [88]:
most_expensive_suburb=average_price.idxmax()

In [89]:
most_expensive_suburb

'Kooyong'

In [90]:
#-------Task5
df.to_csv("newCSV.csv")

In [94]:
#-----Bonus Challenge
median_value=df["Price"].median()

In [99]:
df["category"]=df["Price"].apply(lambda x :"Expensive" if x>median_value else "Affordable")

In [100]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Car,Landsize,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Price_per_room,Year_sold,category
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,2016-12-03,2.5,3067.0,...,1.0,202.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,740000.000000,2016,Expensive
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,2016-02-04,2.5,3067.0,...,0.0,156.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,517500.000000,2016,Expensive
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,2017-03-04,2.5,3067.0,...,0.0,134.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,488333.333333,2017,Expensive
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,2017-03-04,2.5,3067.0,...,1.0,94.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,283333.333333,2017,Affordable
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,2016-06-04,2.5,3067.0,...,2.0,120.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,400000.000000,2016,Expensive

In [102]:
correlation=df["Price"].corr(df["Rooms"])

In [103]:
correlation

0.4966336761865308